services:
  postgres:
    container_name: order_api_postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PG_DATA: /data/postgres
    volumes:
      - ./order-api-postgres-data:/data/postgres
    ports:
      - "5433:5432"